### ISSUE TITLE
libnvidia-ml.so symlink in the wrong location causes issues

### ISSUE THREAD

**Issue by GloriousEggroll** [negativo17/cuda-nvml#1]
libnvidia-ml.so symlink in the wrong location causes issues:

https://github.com/negativo17/cuda-nvml/blob/cd48ade28fa22f0ece5b8c5d88719136e0f22af8/cuda-nvml.spec#L60

In arch and in rpmfusion this symlink is packaged as part of libnvidia-ml, but here it's packaged with cuda-nvml. This leads to issues such as follows:

https://github.com/ilya-zlobintsev/LACT/issues/414

**Comment by scaronni** [comment]
Replied in that issue.

**Comment by scaronni** [comment]
LACT just changed the location. Apparently wherever I look, people use the unversioned library but nobody knows exactly why because it simply was copied over from another project.

The nvml-wrapper library has a pull request open: https://github.com/Cldfire/nvml-wrapper/pull/63
